export const AFFINITIES = [
    { id: 'marketing', group: 'Crecimiento', label: 'Marketing Digital y Redes Sociales' },
    { id: 'sales', group: 'Crecimiento', label: 'Estrategias de Venta y Negociación' },
    { id: 'branding', group: 'Crecimiento', label: 'Branding e Identidad de Marca' },
    { id: 'ecommerce', group: 'Tecnología', label: 'E-commerce y Tiendas Online' },
    { id: 'automation', group: 'Tecnología', label: 'Automatización y Herramientas Digitales' },
    { id: 'finance', group: 'Gestión', label: 'Finanzas y Contabilidad' },
    { id: 'legal', group: 'Gestión', label: 'Aspectos Legales y Formalización' },
    { id: 'logistics', group: 'Operaciones', label: 'Logística y Distribución' },
    { id: 'suppliers', group: 'Operaciones', label: 'Gestión de Proveedores' },
    { id: 'team', group: 'Liderazgo', label: 'Gestión de Equipos y Liderazgo' },
    { id: 'productivity', group: 'Liderazgo', label: 'Productividad y Gestión del Tiempo' },
    { id: 'networking', group: 'Comunidad', label: 'Networking y Alianzas' },
    { id: 'mentoring', group: 'Comunidad', label: 'Mentoría y Acompañamiento' },
    { id: 'innovation', group: 'Innovación', label: 'Innovación y Desarrollo de Productos' },
    { id: 'sustainability', group: 'Innovación', label: 'Sostenibilidad e Impacto Social' },
    { id: 'wellbeing', group: 'Bienestar', label: 'Equilibrio Vida-Trabajo y Bienestar' },
    { id: 'investment', group: 'Financiamiento', label: 'Levantamiento de Capital e Inversión' },
    { id: 'international', group: 'Expansión', label: 'Internacionalización y Exportación' },
    { id: 'public_sector', group: 'Sector Público', label: 'Ventas al Estado y Licitaciones' },
    { id: 'community_management', group: 'Crecimiento', label: 'Gestión de Comunidades' },
    { id: 'seo_sem', group: 'Crecimiento', label: 'SEO/SEM y Publicidad Online' },
    { id: 'content_creation', group: 'Crecimiento', label: 'Creación de Contenido' },
    { id: 'ux_ui', group: 'Tecnología', label: 'Diseño UX/UI' },
    { id: 'data_analytics', group: 'Tecnología', label: 'Analítica de Datos y Business Intelligence' },
    { id: 'cybersecurity', group: 'Tecnología', label: 'Ciberseguridad' },
    { id: 'taxation', group: 'Gestión', label: 'Estrategia Tributaria' },
    { id: 'inventory', group: 'Operaciones', label: 'Gestión de Inventario' },
    { id: 'customer_service', group: 'Operaciones', label: 'Atención al Cliente y Post-venta' },
    { id: 'franchising', group: 'Expansión', label: 'Franquicias y Modelos de Réplica' },
    { id: 'crisis_management', group: 'Liderazgo', label: 'Gestión de Crisis' },
    { id: 'public_speaking', group: 'Liderazgo', label: 'Oratoria y Presentaciones Efectivas' },
    { id: 'fundraising', group: 'Financiamiento', label: 'Fondos Concursables (Corfo, Sercotec)' },
    { id: 'import_export', group: 'Operaciones', label: 'Importaciones y Aduanas' },
    { id: 'intellectual_property', group: 'Legales', label: 'Propiedad Intelectual y Marcas' },
    { id: 'storytelling', group: 'Crecimiento', label: 'Storytelling y Narrativa de Marca' },
    { id: 'photography', group: 'Crecimiento', label: 'Fotografía de Producto' },
    { id: 'video_editing', group: 'Crecimiento', label: 'Edición de Video y Reels' },
    { id: 'event_planning', group: 'Comunidad', label: 'Organización de Eventos y Lanzamientos' },
    { id: 'b2b_sales', group: 'Crecimiento', label: 'Ventas B2B (Empresas)' },
    { id: 'pricing', group: 'Gestión', label: 'Estrategia de Precios' },
    { id: 'market_research', group: 'Innovación', label: 'Investigación de Mercado' }
] as const;

export type AffinityId = typeof AFFINITIES[number]['id'];
export type AffinityGroup = typeof AFFINITIES[number]['group'];
