// USUARIOS REALES actualizados del CSV: export_vista_usuario_pyme_full-6.csv
// Generado el: 2025-11-29T20:35:38.377Z
// Total: 23 usuarios con datos completos

export const REAL_USERS: RealUser[] = [
  {
    email: 'abraham@lofwork.cl',
    name: 'Abraham Lazo',
    companyName: 'lofwork',
    instagram: '@lofwork',
    phone: '+56979982663',
    whatsapp: '+56979982663',
    website: 'https://www.lofwork.cl',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'En 4 semanas ordeno tu modelo, foco comercial y números. Detecto fugas de dinero, corrijo precios, acelero ventas. Plan claro, tareas semanales y seguimiento real. Menos excusas, más clientes.',
    businessDescription: 'Hago que tu negocio pase de caos a crecimiento medible en 4 semanas, con plan claro, ejecución guiada y garantía de resultados.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Abraham Lazo'),
    companyLogoUrl: getLogoUrl('lofwork'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 10000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'c2c3',
    intereses: 'emprendimiento',
    frecuenciaInstagram: '3_4_semana',
    tipoContenido: 'stories',
    experienciaColab: 'ocasional',
    objetivos: 'ventas',
  },
  {
    email: 'Agenciamenfis@gmail.com',
    name: 'Mario Ramirez Arriagada',
    companyName: 'Agencia Menfis',
    instagram: '@agenciamenfis',
    phone: '+56985935460',
    whatsapp: '+56985935460',
    website: 'https://agenciamenfis.cl/',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Paginas web, impresiones, diseño digital, logotipos.',
    businessDescription: 'Menfis es la primera Agencia Boutique de Marketing Digital del sur de Chile.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Mario Ramirez Arriagada'),
    companyLogoUrl: getLogoUrl('Agencia Menfis'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: '',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: '',
    frecuenciaInstagram: '',
    tipoContenido: '',
    experienciaColab: '',
    objetivos: '',
  },
  {
    email: 'akuschel@dtpingenieria.cl',
    name: 'Alejandra Kuschel',
    companyName: 'Centro Elysia',
    instagram: '@elysia_cl',
    phone: '+56994513299',
    whatsapp: '+56994513299',
    website: '',
    category: 'Belleza y Bienestar',
    affinity: 'Bienestar',
    bio: 'Servicios de Manicure y Pedicure',
    businessDescription: 'Enfocados en autocuidado y bienestar.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Alejandra Kuschel'),
    companyLogoUrl: getLogoUrl('Centro Elysia'),
    coverUrl: getCoverUrl('Belleza y Bienestar'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: 'menos6m',
    precioPromedio: '30000',
    generoCliente: 'mujeres',
    rangoEtario: '36a45',
    nse: 'c1c2',
    intereses: 'bienestar - tecnologia - familia - emprendimiento',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'posts - stories - reels - lives - todos',
    experienciaColab: 'frecuente',
    objetivos: 'ventas-visibilidad-networking-colaboraciones',
  },
  {
    email: 'clau7552@gmail.com',
    name: 'Claudia Suárez',
    companyName: 'GroB Pastelería',
    instagram: '@grobpasteleriacl',
    phone: '+56977918833',
    whatsapp: '+56977918833',
    website: '',
    category: 'Gastronomía',
    affinity: 'Gastronomía',
    bio: 'Pastelería',
    businessDescription: 'En Pastelería GroB creamos productos únicos e innovadores, elaborados con ingredientes de alta calidad y un toque creativo que no encontrarás en ninguna otra pastelería.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Claudia Suárez'),
    companyLogoUrl: getLogoUrl('GroB Pastelería'),
    coverUrl: getCoverUrl('Gastronomía'),
    status: 'active',
    followers: 10000,
    firstLogin: true,
    tiempoEmprendimiento: '6m',
    precioPromedio: '30000',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: 'gastronomia - tecnologia - familia - emprendimiento',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'posts - stories - reels',
    experienciaColab: 'aprender',
    objetivos: 'ventas-visibilidad',
  },
  {
    email: 'contacto@globalkidschile.cl',
    name: 'Daniela Peña Lisperguier',
    companyName: 'Global_Kids_Chile',
    instagram: '@Global_Kids_Chile',
    phone: '+56968592280',
    whatsapp: '+56968592280',
    website: 'http://www.globalkidschile.cl',
    category: 'Familia',
    affinity: 'Familia',
    bio: 'Tienda colaborativa de productos infantiles, desde accesorios a productos asociados a la alimentación y lactancia materna',
    businessDescription: 'Tu mundo maternal e infantil en un solo lugar',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Daniela Peña Lisperguier'),
    companyLogoUrl: getLogoUrl('Global_Kids_Chile'),
    coverUrl: getCoverUrl('Familia'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: '6m',
    precioPromedio: '30000',
    generoCliente: 'mujeres',
    rangoEtario: '26a35',
    nse: 'c3d',
    intereses: 'familia - emprendimiento',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'posts - stories - reels',
    experienciaColab: 'ocasional',
    objetivos: 'visibilidad-colaboraciones',
  },
  {
    email: 'cristobal.baier@gmail.com',
    name: 'Cristobal Baier',
    companyName: 'BAW Arquitectura',
    instagram: '@baw_arquitectos',
    phone: '+56987271997',
    whatsapp: '+56987271997',
    website: '',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Baw Arquitectos diseñamos espacios que inspiran y mejoran la vida de las personas. Unimos arquitectura, interiorismo y visión inmobiliaria para transformar ideas en proyectos con alma, belleza y propósito.',
    businessDescription: 'unimos arquitectura, interiorismo y estrategia inmobiliaria para crear espacios que trascienden la estética: proyectos con identidad, equilibrio y alto valor de reventa. Diseñamos viviendas contemporáneas que combinan belleza, funcionalidad y una conexión emocional con el entorno, integrando materiales nobles, luz natural y una visión integral de inversión y habitabilidad.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Cristobal Baier'),
    companyLogoUrl: getLogoUrl('BAW Arquitectura'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: '2anios_años',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: '36a45',
    nse: 'c1c2',
    intereses: 'moda - decoracion - tecnologia - viajes - arte',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'todos',
    experienciaColab: 'aprender',
    objetivos: 'ventas-networking',
  },
  {
    email: 'cuncoaguasclaras@gmail.com',
    name: 'Waldo Lillo Parra',
    companyName: 'Turismoaguasclaras',
    instagram: '@Turismo.aguasclaras',
    phone: '+56941210352',
    whatsapp: '+56941210352',
    website: '',
    category: 'Viajes y Turismo',
    affinity: 'Viajes',
    bio: 'agencia de viajes tour operador y transporte de turistas',
    businessDescription: 'Espacios de salud mental en espacios naturales.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Waldo Lillo Parra'),
    companyLogoUrl: getLogoUrl('Turismoaguasclaras'),
    coverUrl: getCoverUrl('Viajes y Turismo'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: '50.000',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: 'bienestar - gastronomia - familia - deportes - viajes - arte - emprendimiento',
    frecuenciaInstagram: '',
    tipoContenido: 'todos',
    experienciaColab: 'ocasional',
    objetivos: 'ventas-networking-marketing',
  },
  {
    email: 'dafnafinkelstein@gmail.com',
    name: 'Dafna Finlelstein',
    companyName: 'By Turquía',
    instagram: '@byturquia',
    phone: '+56992767707',
    whatsapp: '+569',
    website: 'https:/www.byturtquia.com',
    category: 'Joyería',
    affinity: 'Moda',
    bio: 'Joyas de plata 925 enchapadas en oro de 18 quilates y piedras semipreciosas',
    businessDescription: 'Joyas pensadas en mujeres fuertes, que pueden tener la joya que se merecen a un precio accesible.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Dafna Finlelstein'),
    companyLogoUrl: getLogoUrl('By Turquía'),
    coverUrl: getCoverUrl('Joyería'),
    status: 'active',
    followers: 10000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: '100000',
    generoCliente: 'mujeres',
    rangoEtario: '46a55',
    nse: 'c1c2',
    intereses: 'bienestar - moda - emprendimiento',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'posts - stories - reels',
    experienciaColab: 'frecuente',
    objetivos: 'seguidores-ventas-visibilidad-colaboraciones',
  },
  {
    email: 'doraluz@terraflorpaisajismo.cl',
    name: 'Doraluz Galleguillos',
    companyName: 'Terraflor Paisajismo',
    instagram: '@Terraflorpaisajismochile',
    phone: '+56976160566',
    whatsapp: '+56976160566',
    website: 'HTTPS://www.terraflorpaisajismo.cl',
    category: 'Hogar y Decoración',
    affinity: 'Hogar',
    bio: 'servicios de paisajismo, diseño y construcción de jardines, diseño y construcción de sistemas de riego.',
    businessDescription: 'En Terraflor embellecemos tus proyectos con paisajismo inteligente y sustentable, creando entornos vivos que respetan el agua, promueven la biodiversidad y mejoran la calidad de vida.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Doraluz Galleguillos'),
    companyLogoUrl: getLogoUrl('Terraflor Paisajismo'),
    coverUrl: getCoverUrl('Hogar y Decoración'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'c1c2',
    intereses: 'bienestar - decoracion - emprendimiento - sustentabilidad',
    frecuenciaInstagram: 'ocasional',
    tipoContenido: 'stories - reels - lives',
    experienciaColab: 'ocasional',
    objetivos: 'ventas-visibilidad-networking',
  },
  {
    email: 'ergoguillermogarcia@gmail.com',
    name: 'Guillermo',
    companyName: 'Pausa Coaching',
    instagram: '@pausacoaching',
    phone: '+56979777906',
    whatsapp: '+56979777906',
    website: '',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Soy un coaching para personas o grupos de personas',
    businessDescription: 'Coaching con tiempo de duración',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Guillermo'),
    companyLogoUrl: getLogoUrl('Pausa Coaching'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: '1anio',
    precioPromedio: '100000',
    generoCliente: 'no_aplica',
    rangoEtario: '26a35',
    nse: 'c2c3',
    intereses: 'bienestar',
    frecuenciaInstagram: 'ocasional',
    tipoContenido: 'stories',
    experienciaColab: '',
    objetivos: 'ventas',
  },
  {
    email: 'erwin.madrid.c@gmail.com',
    name: 'Erwin Madrid',
    companyName: 'Garden Smart',
    instagram: '@garden_smartspa',
    phone: '+56962288803',
    whatsapp: '+56962288803',
    website: '',
    category: 'Hogar y Decoración',
    affinity: 'Hogar',
    bio: 'Venta y distribución de pasto natural en rollo',
    businessDescription: 'Es un producto desarrollado por profesionales del rubro, mezcla especialmente diseñada para resistir el alto tráfico y mantener su verdor durante todo el año',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Erwin Madrid'),
    companyLogoUrl: getLogoUrl('Garden Smart'),
    coverUrl: getCoverUrl('Hogar y Decoración'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: '6m',
    precioPromedio: '10000',
    generoCliente: 'mixto',
    rangoEtario: '36a45',
    nse: 'c2c3',
    intereses: 'bienestar - gastronomia - decoracion - familia - deportes',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'stories',
    experienciaColab: 'aprender',
    objetivos: 'ventas-networking',
  },
  {
    email: 'Franvergaraeventos@gmail.com',
    name: 'MARIA FRANCISCA VERGARA',
    companyName: 'Franciscavergaraeventos',
    instagram: '@Franciscavergaraeventos',
    phone: '+56998304686',
    whatsapp: '+56998304686',
    website: '',
    category: 'Eventos',
    affinity: 'Eventos',
    bio: 'Servicio de calidad y innovador',
    businessDescription: 'MI PROPUESTA DE VALOR ES SUBJETIVA',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('MARIA FRANCISCA VERGARA'),
    companyLogoUrl: getLogoUrl('Franciscavergaraeventos'),
    coverUrl: getCoverUrl('Eventos'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: '46a55',
    nse: 'c1c2',
    intereses: 'gastronomia',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'posts - stories - reels',
    experienciaColab: 'ocasional',
    objetivos: 'seguidores-ventas',
  },
  {
    email: 'ghsilva.henriquez@gmail.com',
    name: 'Hayde Silva',
    companyName: 'Natura Hayde',
    instagram: '@natura_hayde',
    phone: '+56985854375',
    whatsapp: '+56985854375',
    website: 'http://www.natura.cl/consultoria/hayde',
    category: 'Belleza y Bienestar',
    affinity: 'Bienestar',
    bio: 'En @Natura_Hayde tenemos productos de Belleza, perfumería y cuidado del cuerpo y rostro para toda la familia.',
    businessDescription: '',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Hayde Silva'),
    companyLogoUrl: getLogoUrl('Natura Hayde'),
    coverUrl: getCoverUrl('Belleza y Bienestar'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: '',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: '',
    frecuenciaInstagram: '',
    tipoContenido: '',
    experienciaColab: '',
    objetivos: '',
  },
  {
    email: 'guille@elevatecreativo.com',
    name: 'Guillermo García',
    companyName: 'Elevate Agencia de Marketing',
    instagram: '@elevate.agencia',
    phone: '+56979777906',
    whatsapp: '+56979777906',
    website: 'https://elevatecreativo.com',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Somos una empresa de servicios de agencia de marketing y asesoría comercial',
    businessDescription: 'Apredemos del negocio del cliente para poder hacer acciones que realmente imparten las ventas.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Guillermo García'),
    companyLogoUrl: getLogoUrl('Elevate Agencia de Marketing'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: '2anios_años',
    precioPromedio: '500000',
    generoCliente: 'no_aplica',
    rangoEtario: '36a45',
    nse: 'mixto',
    intereses: 'emprendimiento',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'stories - reels - lives',
    experienciaColab: 'frecuente',
    objetivos: 'ventas',
  },
  {
    email: 'Klga.aranguiz@gmail.com',
    name: 'Katherine Aránguiz',
    companyName: 'Kinesióloga',
    instagram: '@Kinekatherinearanguiz',
    phone: '+56981298763',
    whatsapp: '+56981298763',
    website: '',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Kinesiología a domicilio Musculoesquelética post cirugías, lesiones y adultos Mayores (zona oriente stgo)',
    businessDescription: '',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Katherine Aránguiz'),
    companyLogoUrl: getLogoUrl('Kinesióloga'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: 'menos6m',
    precioPromedio: '',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: '',
    frecuenciaInstagram: '',
    tipoContenido: '',
    experienciaColab: '',
    objetivos: '',
  },
  {
    email: 'leeda.gonzalez@gmail.com',
    name: 'Keeda González Pinczower',
    companyName: 'Fundación para el bienestar financiero',
    instagram: '@f_bienestarfinanciero',
    phone: '+56934225832',
    whatsapp: '+56934225832',
    website: 'https://www.bienestarfinanciero.org',
    category: 'Educación',
    affinity: 'Educación',
    bio: 'Transformamos vidas a traves de la educación emocional financiera.',
    businessDescription: 'Somos la única organización dedicada a cambiar creencias y hábitos relacionados con nuestra relación con el dinero.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Keeda González Pinczower'),
    companyLogoUrl: getLogoUrl('Fundación para el bienestar financiero'),
    coverUrl: getCoverUrl('Educación'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: 'menos6m',
    precioPromedio: '500000',
    generoCliente: 'mujeres',
    rangoEtario: '46a55',
    nse: 'c2c3',
    intereses: 'bienestar',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'todos',
    experienciaColab: 'aprender',
    objetivos: 'seguidores-ventas-visibilidad-networking-marketing-colaboraciones',
  },
  {
    email: 'lperez@demetra.cl',
    name: 'Leonardo Pérez',
    companyName: 'Demetra',
    instagram: '@demetraspa.cl',
    phone: '+56976143908',
    whatsapp: '+56976143908',
    website: 'https://www.demetra.cl',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Empresa Constructora',
    businessDescription: 'Ofrecer solución integral en obras en el espacio público',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Leonardo Pérez'),
    companyLogoUrl: getLogoUrl('Demetra'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: 'plus500000',
    generoCliente: 'no_aplica',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: '',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'posts - stories',
    experienciaColab: 'ocasional',
    objetivos: 'seguidores-visibilidad-networking',
  },
  {
    email: 'pablo.gonzalez@madsupport.cl',
    name: 'Pablo Gonzalez',
    companyName: 'madsupport',
    instagram: '@madsupport',
    phone: '+56984590309',
    whatsapp: '+56984590309',
    website: 'https://madsupport.cl',
    category: 'Tecnología',
    affinity: 'Tecnología',
    bio: 'desarrollo de app y Diseño Web',
    businessDescription: 'enfocado en la experiencia y ser un partner tecnologico',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Pablo Gonzalez'),
    companyLogoUrl: getLogoUrl('madsupport'),
    coverUrl: getCoverUrl('Tecnología'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: '6m',
    precioPromedio: 'plus500000',
    generoCliente: 'no_aplica',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: 'tecnologia - emprendimiento',
    frecuenciaInstagram: 'ocasional',
    tipoContenido: 'todos',
    experienciaColab: 'aprender',
    objetivos: 'visibilidad-networking',
  },
  {
    email: 'palmahidalgof@gmail.com',
    name: 'Fernando Palma',
    companyName: 'Cross Marketing',
    instagram: '@ferr.fit',
    phone: '+56931149349',
    whatsapp: '+56931149349',
    website: '',
    category: 'Belleza y Bienestar',
    affinity: 'Bienestar',
    bio: 'Servicio de Marketing Digital para Clínicas Estéticas y Clínicas que quieran atraer pacientes',
    businessDescription: 'Atraer pacientes que agenden con resultados en el primer mes',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Fernando Palma'),
    companyLogoUrl: getLogoUrl('Cross Marketing'),
    coverUrl: getCoverUrl('Belleza y Bienestar'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: 'menos6m',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: '36a45',
    nse: 'c2c3',
    intereses: 'bienestar',
    frecuenciaInstagram: 'ocasional',
    tipoContenido: 'stories - reels',
    experienciaColab: 'ocasional',
    objetivos: 'networking-colaboraciones',
  },
  {
    email: 'pamelareyesrivera@gmail.com',
    name: 'Pamela Reyes',
    companyName: 'luna_enfermeria_dermoestetica',
    instagram: '@luna_enfermeria_dermoestetica',
    phone: '+56999309948',
    whatsapp: '+56999309948',
    website: '',
    category: 'Belleza y Bienestar',
    affinity: 'Bienestar',
    bio: 'Servicio de Dermoestética Integral',
    businessDescription: '500.000',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Pamela Reyes'),
    companyLogoUrl: getLogoUrl('luna_enfermeria_dermoestetica'),
    coverUrl: getCoverUrl('Belleza y Bienestar'),
    status: 'active',
    followers: 5000,
    firstLogin: true,
    tiempoEmprendimiento: 'menos6m',
    precioPromedio: '30000',
    generoCliente: 'mujeres',
    rangoEtario: '36a45',
    nse: 'c2c3',
    intereses: 'bienestar',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'posts - stories - reels',
    experienciaColab: 'ocasional',
    objetivos: 'ventas-marketing',
  },
  {
    email: 'patricio.leguia@midirectoriopyme.cl',
    name: 'Patricio Leguia',
    companyName: 'Mi Directorio PyME',
    instagram: '@midirectoriopyme',
    phone: '+56926011422',
    whatsapp: '+56926011422',
    website: 'https://midirectoriopyme.cl/',
    category: 'Servicios Profesionales',
    affinity: 'Negocios',
    bio: 'Consultoría en Estrategia y Finanzas para PyMEs',
    businessDescription: 'COnsultoría de Estrategia para PyMEs: Apoyamos a dueños y socios a lograr mejores resultados financieros y conseguir sus objetivos. Los acompañamos con Diagnósticos, Directorios, Tableros de Control y Planes Estratégicos.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Patricio Leguia'),
    companyLogoUrl: getLogoUrl('Mi Directorio PyME'),
    coverUrl: getCoverUrl('Servicios Profesionales'),
    status: 'active',
    followers: 500,
    firstLogin: true,
    tiempoEmprendimiento: '1anio',
    precioPromedio: 'plus500000',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'c1c2',
    intereses: 'bienestar - gastronomia - tecnologia - familia - deportes - viajes - emprendimiento',
    frecuenciaInstagram: '1_2_semana',
    tipoContenido: 'stories - lives',
    experienciaColab: 'aprender',
    objetivos: 'seguidores-ventas-visibilidad-networking',
  },
  {
    email: 'silvamancilla.camila@gmail.com',
    name: 'Camila Silva Mancilla',
    companyName: 'Paisajismo Locas de Patio',
    instagram: '@paisajismolocasdepatio',
    phone: '+56963094950',
    whatsapp: '+56963094950',
    website: '',
    category: 'Hogar y Decoración',
    affinity: 'Hogar',
    bio: 'Servicio de paisajismo y mantencion de jardines',
    businessDescription: '.',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Camila Silva Mancilla'),
    companyLogoUrl: getLogoUrl('Paisajismo Locas de Patio'),
    coverUrl: getCoverUrl('Hogar y Decoración'),
    status: 'active',
    followers: 10000,
    firstLogin: true,
    tiempoEmprendimiento: '2anios_años',
    precioPromedio: '10000',
    generoCliente: 'mujeres',
    rangoEtario: '36a45',
    nse: 'c1c2',
    intereses: 'decoracion - arte - sustentabilidad',
    frecuenciaInstagram: 'diario',
    tipoContenido: 'posts - stories - reels - lives - todos',
    experienciaColab: 'ocasional',
    objetivos: 'ventas-visibilidad',
  },
  {
    email: 'y.alejandramontilla@gmail.com',
    name: 'Alejandra montilla',
    companyName: 'Bella Vita Estetica',
    instagram: '@bella.vitaestetica',
    phone: '+56930540146',
    whatsapp: '+56930540146',
    website: '',
    category: 'Belleza y Bienestar',
    affinity: 'Bienestar',
    bio: 'Bella Vita Estética es una clínica boutique de belleza integral en Providencia dedicada al bienestar, la estética avanzada y el empoderamiento femenino.',
    businessDescription: '',
    city: 'Santiago',
    avatarUrl: getAvatarUrl('Alejandra montilla'),
    companyLogoUrl: getLogoUrl('Bella Vita Estetica'),
    coverUrl: getCoverUrl('Belleza y Bienestar'),
    status: 'active',
    followers: 1000,
    firstLogin: true,
    tiempoEmprendimiento: 'mas_5anios',
    precioPromedio: '',
    generoCliente: 'mixto',
    rangoEtario: 'mixto',
    nse: 'mixto',
    intereses: '',
    frecuenciaInstagram: '',
    tipoContenido: '',
    experienciaColab: '',
    objetivos: '',
  },
];